name: Build and Test

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install pylint
          
      - name: Run pylint on changed files
        run: |
          # Get list of changed Python files
          CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/main HEAD | grep "\.py$" || true)
          if [ -n "$CHANGED_FILES" ]; then
            python -m pylint --rcfile=.pylintrc $CHANGED_FILES
          else
            echo "No Python files changed"
          fi
          
      - name: Run pytest
        run: |
          pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=warc_processor --cov-report=xml
          
      - name: Install PyInstaller
        run: python -m pip install pyinstaller

      - name: Get version
        id: version
        run: |
          # Read current version
          VERSION=$(python3 -c "exec(open('warc_processor/version.py').read()); print(__version__)")
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Build binary
        run: |
          pip install pyinstaller
          RELEASE_NAME="warc-processor-${{ steps.version.outputs.version }}-linux-x86_64"
          python -m PyInstaller \
            --onefile \
            --name warc-processor \
            warc_processor_main.py

      - name: Package release
        run: |
          RELEASE_NAME="warc-processor-${{ steps.version.outputs.version }}-linux-x86_64"
          RELEASE_DIR="dist/${RELEASE_NAME}"
          mkdir -p "${RELEASE_DIR}"
          cp dist/warc-processor "${RELEASE_DIR}/"
          cp README.md LICENSE "${RELEASE_DIR}/"
          tar czf "dist/${RELEASE_NAME}.tar.gz" -C dist "${RELEASE_NAME}"
          rm -rf "${RELEASE_DIR}"

      - name: Test binary
        run: |
          RELEASE_NAME="warc-processor-${{ steps.version.outputs.version }}-linux-x86_64"
          mkdir -p dist/test_extract
          tar -xzf "dist/${RELEASE_NAME}.tar.gz" -C dist/test_extract
          OUTPUT=$(dist/test_extract/${RELEASE_NAME}/warc-processor --help || true)
          if [[ "$OUTPUT" != *"usage"* ]]; then
            echo "Binary test failed: missing 'usage' in output"
            exit 1
          fi
          echo "Binary test passed"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: warc-processor-${{ steps.version.outputs.version }}
          path: dist/*.tar.gz
          overwrite: true
